### ISSUE TITLE
NPE in RenderManager inject

### ISSUE THREAD

**Issue by DaMatrix** [ValkyrienSkies/Valkyrien-Skies#126]
[fml-client-latest.log](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/1705129/fml-client-latest.log)

This is caused somewhere in https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/blob/master/src/main/java/valkyrienwarfare/mixin/client/renderer/entity/MixinRenderManager.java#L45

**Comment by Rubyjunk** [comment]
This file has been modified a lot since this issue, is it still applicable?

**Comment by Tri0de** [comment]
¯\\\_(ツ)\_/¯
