### ISSUE TITLE
Wings mod incompatibility

### ISSUE THREAD

**Issue by enderplayer2001** [ValkyrienSkies/Valkyrien-Skies#210]
After carefully removing and re-adding mods to my modpack to find the source of a crash, i found out that when used with the mod Wings by pau101 the game crashes without loading. It gives no crash report and doesn't open the game's window. After looking at the game's log, i came across the following:

12:28:20	mixin	main	Mixin prepare failed preparing entity.MixinEntityIntrinsic in mixins.valkyrienwarfare.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.valkyrienwarfare.json:entity.MixinEntityIntrinsic target net.minecraft.entity.Entity was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.valkyrienwarfare.json:entity.MixinEntityIntrinsic target net.minecraft.entity.Entity was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856)
   (...)
Below goes the full log.
[latest.log](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/2727311/latest.log)
i've also warned the creator of Wings of this issue.

**Comment by Rubyjunk** [comment]
Hi, thanks for reporting this mod incompatibility issue! I appreciate every single report we get, so don't stop sending them. That said, we have a lot of work set out for us in release v1 of Valkyrien Warfare and therefore fixing game-breaking bugs and making the mod's experience more stable, fun, and consistent is our number one priority.

**What this means for you:** we might not be fixing this bug that soon. However, keep reporting these issues to us, it's really helpful and allows us to fix them when we get a chance.

-----
With <3,
Valkyrien Warfare Team
