### ISSUE TITLE
Dynamic Trees animation bug

### ISSUE THREAD

**Issue by koravel** [ValkyrienSkies/Valkyrien-Skies#214]
Normally, when tree is chopped, falling animation is playing.
With ValkyrienWarfare mod this animation brokes.
It looks like tree is freeze and then falls very quickly.

I'm not sure is that because Valkyrien Warfare  or Dynamic Trees itself...

Mods versions:
ValkyrienWarfare-0.9_prerelease_5+[Optimization+Update]
DynamicTrees-1.12.2-0.9.4

**Comment by Rubyjunk** [comment]
Hi, thanks for reporting this mod incompatibility issue! I appreciate every single report we get, so don't stop sending them. That said, we have a lot of work set out for us in release v1 of Valkyrien Warfare and therefore fixing game-breaking bugs and making the mod's experience more stable, fun, and consistent is our number one priority.

**What this means for you:** we might not be fixing this bug that soon. However, keep reporting these issues to us, it's really helpful and allows us to fix them when we get a chance.

-----
With <3,
Valkyrien Warfare Team

**Comment by Deliphin** [comment]
Just FYI, I see a very similar issue right now.

Dynamic Trees 1.12.2-0.9.19  
Valkyrien Skies Control 1.12.2-1.1.0  
Valkyrien Skies Core 1.12.2-1.1.0  
Valkyrien Skies World 1.12.2-1.0.0

What happens for me is I break a tree, then for a frame the tree completely fills my screen for some reason, then the tree is just gone. The tree's drops still occur, but the animation doesn't play.

**Comment by ShiratsuYudachi** [comment]
Good news, look like this bug have already been fixed in version 1.1.3

**Comment by Tri0de** [comment]
Very cool :D
