### ISSUE TITLE
[1.12.2] A Wild Fairly Lights Conflict Appears!

### ISSUE THREAD

**Issue by Scarlet-Phonavis** [ValkyrienSkies/Valkyrien-Skies#273]
Seemingly completely different than #90 
https://pastebin.com/TA2am5gp

I'm dumb, forgot to mention it only appears when switching dimensions as far as I can tell, loading is fine normally, but if you say, go to "Yet another mining dimension" and back it'll cause the issue.

**Comment by Rubyjunk** [comment]
You are currently using an outdated version of the mod, from curseforge. Note that updating will cause issue #279
