### ISSUE TITLE
Another Fairy Lights Conflict

### ISSUE THREAD

**Issue by korlandril** [ValkyrienSkies/Valkyrien-Skies#279]
https://paste.dimdev.org/ecememimuz.rb
Seems to be different from #273 ? 

Using build 461

**Comment by Rubyjunk** [comment]
Fairy Lights has integration with an older version of Valkyrien Warfare, and this integration is causing it to fail with the newer version of the VW API. I imagine that this issue will not be fixed until the new version of Valkyrien Warfare is considered stable.
