### ISSUE TITLE
Ships going from 0.9.5 to revamped no longer work.

### ISSUE THREAD

**Issue by jangofett890** [ValkyrienSkies/Valkyrien-Skies#282]
Wanted to make my ship "disassembled" so made a backup and updated the mod, the physics infuser has the three options grayed out but instead of assemble says disassemble, even with all physics cores placed in. using 
Updated from ValkyrienWarfare-1.12.2-0.9.5-universal.jar
to 
ValkyrienWarfareRevamped-1.12.2-0.9a-full-jenkins-461.jar

**Comment by MrSalimoc** [comment]
For disassembling the ship, you need to align it.

**Comment by jangofett890** [comment]
no I don't think you understand. 
I can't even fly the ship, all options of the physics infuser(it has all the cores placed in it too) are grayed out if I place it on a pre-existing ship that was created in the non-revamp version/0.95. 
If there is a way to align/disassemble in 0.9.5 that would be great to know.

**Comment by MrSalimoc** [comment]
I don't think this is possible. To see with a developer..
For aligning ship in 0.9.5 you need to do it manually.

**Comment by Rubyjunk** [comment]
You cannot align a ship in 0.9.5. I will look into a conversion tool but it may turn out to be a waste of development time if too difficult. Sorry:(

Perhaps you could try getting your ship out of subspace by looking at the coordinates of each ship block and using mcedit to take them back in to the normal world (therefore "de-infusing" them manually?)

**Comment by Rubydesic** [comment]
yea, not doing it, sorry
