### ISSUE TITLE
Sneaking on an airship does not let you walk.

### ISSUE THREAD

**Issue by DeltaNedas** [ValkyrienSkies/Valkyrien-Skies#284]
Tested in jenkins 460.
Enable physics for a ship and sneak.
You will notice that you cannot move.
ples fix

**Comment by Anatoly03** [comment]
Try clicking shift

**Comment by DeltaNedas** [comment]
10 million iq
if i want to build on an airship for example i would want to sneak *and* walk at the same time as to not fall off

**Comment by Rubydesic** [comment]
fixed
