### ISSUE TITLE
Large ships not working, and jank on all ships. 1.12.2 universal and prerelease on a server.

### ISSUE THREAD

**Issue by LordTouchMeAgain** [ValkyrienSkies/Valkyrien-Skies#291]
to keep things short, the idea is amazing but all ships feel really laggy, as for large ships we have a carrier over 10k blocks and with all tested to be working mod blocks. but the first time we tried it said it was too large, we changed teh limit to 100k and since have not received any notices, but it still does not work.

**Comment by Rubyjunk** [comment]
It's being looked into.

**Comment by LordTouchMeAgain** [comment]
Mod list of the server includes actully additons, AE2, Biomes O plenty, Carpenters beta 1.12.2, Chisel, Code chicken, Cofcore % world, conarm, CTM, doggy talents, enderstorage, extra utilities, Extreme reactors, Flans gun mod and its submods, forestry for minecraft,  Forgelin, Galacticcraft and its planets submod, gravestone, simple harvest, industrial foregoing, Jei and NEI, Journy map, lost cities, mantle, mcjtylib, Mekanism and generators submod, micdoodle, modular power suits, Neat+, numinia, omlib, openmodular turrets, optifine, oreexcavation, redstone flux, rftools, tinkers -its armor and leveling submods, teslacore lib, all thermal expansion mods, Wawla, & zerocore

**Comment by Sunspot0411** [comment]
You have tooooooo many mods on your server, that's probably the reason why it's laggy. As for large ship, are you using the newest version? if so then try commend /physsettings maxshipsize 100000 to increase max ship size

**Comment by LordTouchMeAgain** [comment]
"10k blocks and with all tested to be working mod blocks. but the first time we tried it said it was too large, we changed teh limit to 100k and since have not received any notices, but it still does not work."


as for the lag, i don't believe it to be related to the mods, as nothing else lags, example when someone uses a ship the ship is spazaming back and fourth while moving forwards. but i on land don't notice anything. We tried changing the render distance to no aveil.

**Comment by Rubyjunk** [comment]
Could you give us some insight into your server performance at this time? When these issues are happening, what is your physics tps (`/vw tps`) and your in-game tps (`/forge tps`)?

**Comment by LordTouchMeAgain** [comment]
I will see when i can get this data, with school starting i am very busy get to you soon.

**Comment by Sunspot0411** [comment]
could you tell what vw version are you using? the size increasing command definitely works with the newest vw version, as I have tested many times

**Comment by LordTouchMeAgain** [comment]
We are running 1.12.2 Universal,

**Comment by Sunspot0411** [comment]
that's wired, /physsettings maxshipsize 10000 works for me, and i'm using the same version. I also don't have lag issue. maybe you should remove all mods and re-add them one by one, so that you could check if it is some mod conflicts.

**Comment by Rubyjunk** [comment]
@LordTouchMeAgain Do you get any sort of message in the console when you try to assemble ship?

**Comment by LordTouchMeAgain** [comment]
we are about to launch the server again, last tim ewe played after we changed the size limit, we did not recive any pop ups, instead we press assemble and nothing happens.

**Comment by LordTouchMeAgain** [comment]
Phys tps is 50.59     in game tps =
![data minecraft](https://user-images.githubusercontent.com/44792410/63206702-3c815800-c07f-11e9-8302-acba1232ac3a.png)

**Comment by Rubyjunk** [comment]
Hi, the lag might be attributed to your physics TPS (50.59) which is supposed to run at 100.00 TPS. However, this does not solve the issue of your ship not assembling. I believe I have reproduced this issue, however, could you go into your server **console** (not in-game), and see if there are any errors when you try to press assemble ship? Thanks!

**Comment by LordTouchMeAgain** [comment]
I will have to ask the host to do that, will do when i can.

**Comment by Rubydesic** [comment]
Everything seems to be working fine on servers,
