### ISSUE TITLE
Better Diving mod potential incompatibility

### ISSUE THREAD

**Issue by TheSpiderDungeon** [ValkyrienSkies/Valkyrien-Skies#295]
As I say, it's **potentially** BD, because I have almost 200 mods, and it could be any of them. However, the logs say Better Diving errored while loading, so here's the log it gave me:

https://pastebin.com/AD4Pvhhd

**Comment by Rubyjunk** [comment]
I mean... I don't even think this is caused by Valkyrien Warfare. If you remove the mod, does the crash go away?

**Comment by TheSpiderDungeon** [comment]
Yep. If I remove Valkyrien Warfare, the game works fine. However, if I remove Better Diving, it still crashes oddly enough.

Here's a list of the mod .jars if it helps:
![image](https://user-images.githubusercontent.com/14132982/63401056-69e64280-c3ac-11e9-97fb-bd71c2847c84.png)
