### ISSUE TITLE
Ship only move backwards

### ISSUE THREAD

**Issue by CaptainBaconator** [ValkyrienSkies/Valkyrien-Skies#299]
I'm unsure why, but in every build I've played, the ships only move in the direction the propeller is facing. Ex: a ship with the prop on the back can only move backwards, regardless of whether the chadburn says ahead or astern.

**Comment by zayats1** [comment]
Place Gearbox in right position

**Comment by CaptainBaconator** [comment]
it is, i mean my ship is the EXACT same ship shown in the instructions

**Comment by traverseda** [comment]
After extended testing I have discovered that

 * Gearboxes don't seem to be able to go in reverse
 * The props go on the *front* of the airship, you can't use them to push the airship.
