### ISSUE TITLE
Got a crash when trying to start engine after increase ship altitude

### ISSUE THREAD

**Issue by Sunspot0411** [ValkyrienSkies/Valkyrien-Skies#304]
[crash-2019-08-25_22.15.04-server.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/3539174/crash-2019-08-25_22.15.04-server.txt)

**Comment by Best108** [comment]
I'm not really sure if this is caused by valkyrien skies. Is this bug reproducible?
