### ISSUE TITLE
Configure speed and other things

### ISSUE THREAD

**Issue by Camperfrosch** [ValkyrienSkies/Valkyrien-Skies#308]
I would love to be able to configure the speed of things individually instead of the entire physics.

with /physsettings physicsspeed it will make everything go faster, even the turbulences.
It would be nice if you could power ships somehow so they will become faster. 
But also have an option added, which sets the speed of a ship fix as an operator.

In general, it would be nice if you could configure some more. I know it is a lot of work, I am just wishing for things ^_^

**Comment by Rubydesic** [comment]
vs control engines have configurable thrust
