### ISSUE TITLE
Rename item IDs

### ISSUE THREAD

**Issue by Rubydesic** [ValkyrienSkies/Valkyrien-Skies#310]
Rename confusing item ids like ethereumore to ethereum_ore, etc.

**Comment by DeltaNedas** [comment]
valkyrium_ore*

**Comment by zayats1** [comment]
Remove mod id   limit for 1.14 version?

**Comment by DeltaNedas** [comment]
there is no 1.14 version
mod id limits is not a problem, if it was we could use mod ids and data values
