### ISSUE TITLE
Beds not functioning once ship is assembled.

### ISSUE THREAD

**Issue by Pettmybuckets** [ValkyrienSkies/Valkyrien-Skies#327]
Beds that have been placed on an airship no longer spawn players after the ship has been constructed or moved. At night while in flight right clicking the bed will only display the message "spawn point set" but does to re-spawn the player upon death. even after the ship has been re-aligned and disassembled the player does not re-spawn at the bed.  one possible cause could be linked to another issue with placed items like red stone, levers, beds and mine cart tracks will "break" continuously during flight, dropping their items  while not really breaking. this deserves a post of its own though.

**Comment by Rubydesic** [comment]
Are you using any other mods? Cannot reproduce this issue.

**Comment by Pettmybuckets** [comment]
he mods im currently using are age of weapons, backpack, OTG, Biom bundle, grapple hook, JEI, loot bags, llibrary, mowzies mods, rouge like dungeons, and the twilight forest. im using version 0.9.2

**Comment by Rubydesic** [comment]
Does this issue occur with the latest master version?
