### ISSUE TITLE
Player is too tall when RandomPatches is installed

### ISSUE THREAD

**Issue by seancrain** [ValkyrienSkies/Valkyrien-Skies#333]
I don't know how far back this issue goes, but it seems recent. When the latest build of Valkyrien Skies is installed, you view the world from too far off the ground. In F5 mode, you can see that your character is on the ground, but you're viewing them from well above them.

![2019-09-10_19 13 10](https://user-images.githubusercontent.com/38871906/64812142-41dd9f80-d564-11e9-9159-45495dd1258e.png)

**Comment by seancrain** [comment]
@Rubydesic I have identified what is causing this.

This problem occurs when this mod is installed alongside RandomPatches by @TheRandomLabs.

**Comment by TheRandomLabs** [comment]
This was happening because Valkyrien Skies overwrites `EntityRenderer#orientCamera`, and RandomPatches modified the same method. To fix this, I moved RandomPatches' patch out of `EntityRenderer#orientCamera` and into `EntityRenderer#setupCameraTransform`.
