### ISSUE TITLE
Pick up items from bellow ground

### ISSUE THREAD

**Issue by CitizenFoffie** [ValkyrienSkies/Valkyrien-Skies#335]
can I not pick up dirt because I blew up the ground?

**Comment by Rubydesic** [comment]
I don't understand your question.

**Comment by CitizenFoffie** [comment]
Sorry I was having a stroke (sarcasm) I have a tnt cannon on my ship and you know how you explode the ground and it drops items? for some reason I get those items in the air. when it's on the ground. Weird, I looked in the cfg file to see if it was optional, didn't fine anything

**Comment by Sunspot0411** [comment]
so what vw version are you using?

**Comment by DeltaNedas** [comment]
what you are referring to as vw is in fact vs, or as ive recently taken to calling it, valkyrien skies

**Comment by Sunspot0411** [comment]
Cause I had a feeling that he was using old version when it was still called vw

**Comment by CitizenFoffie** [comment]
The newest 1.12.2 version 1.12.2-0.9

**Comment by DeltaNedas** [comment]
no its not silly sausage

**Comment by CitizenFoffie** [comment]
I clicked the download so it's the stable newest one for 1.12.2

**Comment by DeltaNedas** [comment]
doesnt mean its latest by any means. 1.0 is the latest version

**Comment by Sunspot0411** [comment]
no, it is not the newest version

**Comment by Rubydesic** [comment]
closed, this is fixed in newer versions
