### ISSUE TITLE
Re-add settings command but for all config values

### ISSUE THREAD

**Issue by Rubydesic** [ValkyrienSkies/Valkyrien-Skies#338]
Re-add the /physsettings command with a more general approach that automatically allows values in the config to not only be edited through the native forge GUI but also through a command.

**Comment by DeltaNedas** [comment]
bad idea, it dumbs down the mod for little to no benefit
just stick with the gui, kiddies dont understand commands anyways

**Comment by Rubydesic** [comment]
it's required to edit config in game on servers, unfortunately

**Comment by Rubydesic** [comment]
keyword: in game

Feature has been added
