### ISSUE TITLE
Unable to Respawn

### ISSUE THREAD

**Issue by Pettmybuckets** [ValkyrienSkies/Valkyrien-Skies#342]
Players are unable to respawn after dying. it gives me the option to either respawn or go to title screen, but then when you go to click on either the game just sits there and does nothing. sometimes the world unloads and goes transparent but still kinda freezes. you can still move your mouse and click either option but with no reaction. this happens on our server as well as in single player. a certain mod combination could be the cause.
[2019-10-15-1.log.gz](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/3727478/2019-10-15-1.log.gz)
[2019-10-15-2.log.gz](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/3727479/2019-10-15-2.log.gz)

**Comment by sashan13** [comment]
I am also having said issue. Can't provide logs but updating Valkyrien around 10 days ago was what started it on my build.
Also happens when playing on LAN, both to me and players that connect to me. Can be fixed after connecting or entering the world under different nickname.

**Comment by Rubydesic** [comment]
Fixed on latest circle build
