### ISSUE TITLE
Crash on world load or creation // No other mods installed.

### ISSUE THREAD

**Issue by ValianceHD** [ValkyrienSkies/Valkyrien-Skies#343]
Worth noting this happens with the most recent 1.12.2 version as well. Unable to touch this mod for the time being.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoaderForge (Valkyrien+Warfare+0.9_pre_3+[HotFix].jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10/30/19 2:27 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.World.func_175725_q(World.java:4686)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:475)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4039186384 bytes (3852 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 5 total; -Xms4096m -Xmx4096m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID               | Version      | Source                                   | Signature                                |
	|:------ |:---------------- |:------------ |:---------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft        | 1.12.2       | minecraft.jar                            | None                                     |
	| LCHIJA | mcp              | 9.42         | minecraft.jar                            | None                                     |
	| LCHIJA | FML              | 8.0.99.99    | modpack.jar                              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge            | 14.23.5.2836 | modpack.jar                              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | valkyrienwarfare | 0.9_alpha    | Valkyrien+Warfare+0.9_pre_3+[HotFix].jar | None                                     |

	Loaded coremods (and transformers): 
MixinLoaderForge (Valkyrien+Warfare+0.9_pre_3+[HotFix].jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by Rubydesic** [comment]
Hi, it looks like this issue is obsolete and is fixed in the latest builds of the mod. Thanks for taking the time to report this issue.

Please observe instructions on how to download the latest v0 or v1 version of the mod from the wiki page: https://wiki.valkyrienskies.org/wiki/Development_Builds.

If you have any concerns feel free to ask.

**Comment by DeltaNedas** [comment]
i agree, pls close

**Comment by Rubydesic** [comment]
Reopen if you have any issues.
