### ISSUE TITLE
Crash with Build 155

### ISSUE THREAD

**Issue by seancrain** [ValkyrienSkies/Valkyrien-Skies#352]
On the client side, it throws up an issue and blames Iron Chests:
[crash-2019-11-21_12.55.32-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/3876256/crash-2019-11-21_12.55.32-client.txt)

On the server side, with the same set of mods, Iron Chests is not blamed:
[crash-2019-11-21_12.56.43-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/3876260/crash-2019-11-21_12.56.43-server.txt)

I noticed that I downloaded the latest breaking build instead of the master build. I have downloaded 153, and it seems to be working.

**Comment by DeltaNedas** [comment]
will try to replicate later
