### ISSUE TITLE
Spawn Wither and Break the End Crystal will show some errors

### ISSUE THREAD

**Issue by SIZStan** [ValkyrienSkies/Valkyrien-Skies#373]
And when get into the End world. Break the End Crystal will show some errors
https://paste.ubuntu.com/p/NMFCXG8qb8/
When Wither spawn, it will show the some error message(but a little different)
https://paste.ubuntu.com/p/snYqCp9G75/
(All test in an official forge server)

**Comment by Rubydesic** [comment]
The pastes are showing 404s.
