### ISSUE TITLE
IllegalStateException on world creation

### ISSUE THREAD

**Issue by jdw-mis** [ValkyrienSkies/Valkyrien-Skies#376]
Appears to be related to the OpenJ9 JVM?
[crash-2020-03-01_03.52.39-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/4271734/crash-2020-03-01_03.52.39-server.txt)
[crash-2020-03-01_04.01.39-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/4271735/crash-2020-03-01_04.01.39-server.txt)
First is 1.0-Alpha-1, second is breaking/1.0 build 213

**Comment by DeltaNedas** [comment]
openj9 is not supported at all, use hotspot

**Comment by Rubydesic** [comment]
As said above, we are not testing on OpenJ9 at this time.

**Comment by gatoborrachon** [comment]
just a little doubt: there is 0% probable that OpenJ9 will be supported in the future?

**Comment by gatoborrachon** [comment]
@jdw-mis this issue was fixed by OpenJ9 side, you can get the latests releases here:
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2020-12-10-04-05/OpenJDK8U-jdk_x64_windows_openj9_2020-12-10-04-05.zip
