### ISSUE TITLE
Console spam of "Price of write"

### ISSUE THREAD

**Issue by Fureniku** [ValkyrienSkies/Valkyrien-Skies#378]
It's pretty annoying!

Could we get a configurable debug option, with this only printing when that's enabled?

(print in question: https://github.com/ValkyrienSkies/Valkyrien-Skies/blob/master/src/main/java/org/valkyrienskies/mod/common/physmanagement/shipdata/QueryableShipData.java#L202)

**Comment by Rubydesic** [comment]
fixed
