### ISSUE TITLE
User swtiching controls doesn't dynamically change

### ISSUE THREAD

**Issue by gilmorejohn** [ValkyrienSkies/Valkyrien-Skies#381]
Particularly the VS Wrench. I rebound my controls for the shift button, but VS wrench never changed from saying "Press Shift + Right Click to Switch Between Mods", and it took me forever to realize that it wasn't shift that I needed to be pressing. If it's possible, poll users control settings and change the string dynamically.

**Comment by Rubydesic** [comment]
fixed
