### ISSUE TITLE
Camera Wings mod.

### ISSUE THREAD

**Issue by SpongeDuck** [ValkyrienSkies/Valkyrien-Skies#382]
Hi,
When using the Wings mod  the camera hovers above the players character, 
I saw people have reported this in the past as well.
i thought it would be cool to use them together on our server so this was kinda a bummer.
Thanks for reading!!!!

**Comment by Tohricat** [comment]
When I tested, it was an issue with Random Patches.

**Comment by IStole** [comment]
Yeah me too with wings mod you have a problem with the camera view!

**Comment by Tri0de** [comment]
Fixed in 1.1.6
