### ISSUE TITLE
Laggs on Multiplayer Server!!!

### ISSUE THREAD

**Issue by IStole** [ValkyrienSkies/Valkyrien-Skies#384]
Hi, the mod is lagging with 10 GB RAM (only the mod), and we are only to 3rd on the server. The mod is the best ive ever seen and together it makes a lot of fun! But its laggin??? Why. "DieBuddiesZocken Airbattle" have a video with a lagg free gameplay on a server but on my server its laggin :C

Video with laggfree gameplay: https://www.youtube.com/watch?v=Wwkf__PX888
pls make it happen on my server :C

**Comment by DeltaNedas** [comment]
why on gods good earth did you allocate 10gb ram for 1 (one) mod

**Comment by IStole** [comment]
öhm cause i have enough xd. And I thought it woud be laggfree if i give it 10 GB xd.

**Comment by IStole** [comment]
do you think the lag is comming from too much ram? I Test it

**Comment by IStole** [comment]
nah its still laggin
:C

**Comment by Rubydesic** [comment]
I need to know what version of the mod you are using (and where you downloaded it from)

**Comment by IStole** [comment]
Downloaded it from: https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies/download/2570337

Version: ValkyrienWarfare-1.12.2-0.9.5-universal.jar, cause the newest isnt working with wings mod and i think a little more complicatet for the start :)

**Comment by IStole** [comment]
Testet the newest without wings mod, its still lagging idk :) Hop you can fix it. GL :)

**Comment by DeltaNedas** [comment]
1. skipping ticks means your cpu sucks
2. more ram will not increase fps
3. always use latest version
4. womm

**Comment by IStole** [comment]
What can i do if my cpu sucks? :C

**Comment by IStole** [comment]
Ive testet my cpu with Cpu-Z, and task manager. It was stable on 16% min to 42% max workload.
The Temperature was max 62° degree. Stress tests say my cpu is okay and fine idk... what i do now .-.
In singleplayer all is laggfree and it makes lot of fun to play!

**Comment by IStole** [comment]
Windows

CPU: AMD Ryzen 7 3700X on 4,2 GHz

GPU: NVIDIA GeForce 1660TI

**Comment by IStole** [comment]
And i want to stay on windows xd

**Comment by IStole** [comment]
And testet the mod on other server Plattforms like Aternos, Serverpro and stuff like that, there its laggin too. Maybe the mod needs a very very good cpu? idk

**Comment by Rubydesic** [comment]
IStole, we don't support older versions. Please use the latest version and reopen if the issue persists.

**Comment by DeltaNedas** [comment]
thats a lot better than my 2ghz i3 laptop, your os and old mod version is the problem
