### ISSUE TITLE
[Suggestion] Config for Valkyrium oregen

### ISSUE THREAD

**Issue by Uub112** [ValkyrienSkies/Valkyrien-Skies#393]
One of the things I noticed about this mod as I've been playing with the configs and putting it into modpacks is that there's no way to control how valkyrium generates, whether that be height, blocks it spawns in, dimension, or whether it generates at all, and it would be nice if there would be a config of some kind for the ore generation, even if it's just an option to disable valkyrium from generating.

**Comment by Rubydesic** [comment]
Closed by #394, thanks hakasapl
