### ISSUE TITLE
Plasma engines 

### ISSUE THREAD

**Issue by alnega31** [ValkyrienSkies/Valkyrien-Skies#395]
Hi everyone, 
i'm having problems with plasma engines and cannons:
1º How do you use them?
2º When I start the game with the plasma engines and the plasma cannons the game crashes. Is there going to be any fix to it?. Thanks to everyone

**Comment by Sunspot0411** [comment]
You need IC2 installed for plasma cannon. As for how to use them check on the pinned message at #plasmacannon channel on discord.

**Comment by alnega31** [comment]
Ok thanks for that. I also wanna know how to control the speed of the plasma engine if it's possible because I have been trying to slow it but it doesn't.

**Comment by Sunspot0411** [comment]
you can change it's pushing force by changing the number of plasma controllers behind it. but you cannot change it if you have only the plasma engine block. it is designed for heavy ships

**Comment by alnega31** [comment]
OK thanks a lot. You are saying that with more blocks more it pushes right?

**Comment by Sunspot0411** [comment]
yes, the more plasma controllers you put behind an engine the more thrust you get. similar for plasma cannons, the more plasma generator(not controller) you put behind a cannon, the more blast power you get.

**Comment by alnega31** [comment]
Ok thanks a lot. It was nice having you as help.

**Comment by DeltaNedas** [comment]
plasma engines are unrelated to vs

**Comment by Sunspot0411** [comment]
> plasma engines are unrelated to vs

no, plasma engines are designed for vs, and needs vs as dependency

**Comment by DeltaNedas** [comment]
yes but its an issue with plasma engines not vs report it there

**Comment by Rubydesic** [comment]
The issue is already resolved, let's just leave this.
