### ISSUE TITLE
Game crashes when loading a save

### ISSUE THREAD

**Issue by RisingInIris2017** [ValkyrienSkies/Valkyrien-Skies#400]
#### Mod version:

1.0-alpha-1

#### Forge version:

1.12.2-14.23.5.2854

#### Singleplayer or Multiplayer:

Singleplayer.

#### Installed mods:

Attached in the crash report.

## Link to full crash log

https://paste.ubuntu.com/p/6HJqpZzNYM/

#### How to reproduce:

1. Start the game.
2. Load an old save created with Valkyrien Skies 0.95 installed.
3. Game crashes.
4. I have tried not to use Eclipse OpenJ9 to launch my Minecraft instance.
I used other Java Runtime Environment, normal JRE for example, but the game crashed, too.
5. Use Valkyrien Skies 0.95, and the save will load normally.

I do not sure whether this issue is due to my JRE or not, but I think it will be helpful to report this issue to you.
I will appreciate your kind-hearted help.
Thanks in advance.

**Comment by hoobooh** [comment]
pretty sure server tick loop errors are caused by version conflicts

**Comment by Sunspot0411** [comment]
try remove all the engines and compressors on your ship on VS 0.95 and then load the save on the last VS version

**Comment by Rubydesic** [comment]
There is no intention to make saves from 0.95 compatible with latest release, sorry.

**Comment by gatoborrachon** [comment]
@RisingInIris2017 this issue was fixed by OpenJ9 side, you can get the latest release here:
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2020-12-10-04-05/OpenJDK8U-jdk_x64_windows_openj9_2020-12-10-04-05.zip
