### ISSUE TITLE
Server side: huge error page(with ZombieAwareness)

### ISSUE THREAD

**Issue by HuangAdam** [ValkyrienSkies/Valkyrien-Skies#403]
Only three mods:
![瓦尔基里与僵尸意识bug](https://user-images.githubusercontent.com/46439030/90292859-56819080-deb5-11ea-976e-00fd982ed33a.png)
This is the log.
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/5077269/latest.log)
When any player enters the server, numerous errors are reported from the console.

I have tried other version mod. It's same.
Server: [Catserver](https://catserver.moe/)
CatServer-c2fd278-universal.jar

**Comment by Tri0de** [comment]
lol

**Comment by HuangAdam** [comment]
> lol

Can you tell me how to use the newest version?
It lost most item than older version.
Only two chairs?

**Comment by Rubydesic** [comment]
use an older version
