### ISSUE TITLE
Forge server crashes

### ISSUE THREAD

**Issue by rainbowsheepw** [ValkyrienSkies/Valkyrien-Skies#405]
I took valkyrium ore out of forge server in 1.12.2, and then I threw it out. The server twitched for a while and then crashed. The mod version is 1.0-alpha-1

**Comment by Sunspot0411** [comment]
It could be your server memory is not enough

**Comment by Rubydesic** [comment]
Hi, can you test if this issue is still present on the master branch?

**Comment by Rubydesic** [comment]
cannot replicate
