### ISSUE TITLE
Exit code: 0

### ISSUE THREAD

**Issue by ym1025** [ValkyrienSkies/Valkyrien-Skies#407]
When I pressed "Play" button on the launcher, it said "Exit code: 0".
MC logo wasn't displayed.

mod list: https://hastebin.com/ufamenaqed.nginx
latest.log: https://hastebin.com/saseqeguwu.md

forge version: 2854

**Comment by Sunspot0411** [comment]
what launcher did you use? it does not seem like an official launcher.

**Comment by ym1025** [comment]
I used twitch launcher.
The problem occurred in MultiMC too.

**Comment by Rubydesic** [comment]
You have too many mods to narrow down the problem, reopen if you know which mod causes the incompatibility or the issue occurs with no other mods.
