### ISSUE TITLE
An assembled ship will lose texture if I look up at it.

### ISSUE THREAD

**Issue by 694895066** [ValkyrienSkies/Valkyrien-Skies#411]
If I run the game without the Optfine mod, or with that mod but setting the shader option as "OFF" (instead of "Internal"), the texture of the assembled ship's blocks will all be rendered as solid color (mostly light blue) if I look up (at an angle above 45 degrees, more or less?) at the ship, this texture issue could occur both inside and outside the assembled ship.

Running the game with the Optfine mod and choosing the "internal" shader option would indeed avoid the problem, although some other mods will have glitch (e.g. Flan's mod) or stop working (e.g. Colored Lights mod). Since the Optfine mod is an additional mod after all, I wonder if this problem should be deemed as a bug or an incompatible issue.

In addition, when I run the game with the Optfine mod and the shader setting as "OFF", if I dive into the sea (or any other water that deep enough and outside the assembled ship, I guess?), look up at the assembled ship, then get out of the sea, the texture issue will be somehow alleviated (texture will be faded, but not solid color anymore, which is much more tolerable).

I'm using the latest update 1.0 for 1.12.2.

**Comment by Sunspot0411** [comment]
You need to set shaders up before entering a world to avoid this issue. I am using seus renewed shaders on my side and there is no compatibility issue.

**Comment by Sunspot0411** [comment]
And there could be some additional compatibility issues with other mods instead of optifine. Or could be some optifine settings you need to turn off, like fast math for example. I suggest you tweak around with optifine settings first and see if the problems still exist. But remember you may need to quit and re enter the world every time you change optifine settings. I have been played vs on both client and server for a long time, never had such issues with optifine.

**Comment by 694895066** [comment]
> And there could be some additional compatibility issues with other mods instead of optifine. Or could be some optifine settings you need to turn off, like fast math for example. I suggest you tweak around with optifine settings first and see if the problems still exist. But remember you may need to quit and re enter the world every time you change optifine settings. I have been played vs on both client and server for a long time, never had such issues with optifine.

Thanks for replying. Although in my case, the issue aforementioned occurs WITHOUT the Optifine mod, thus I thought it might be a bug that need to report.

**Comment by 694895066** [comment]
> This should not be a vs problem, what other mods did you have?

You are right, it turns out that the Albedo mod is the one causing the problem. Sorry for all the trouble caused by my negligence.
