### ISSUE TITLE
Rudders do not turn the ship?

### ISSUE THREAD

**Issue by RaydenX77** [ValkyrienSkies/Valkyrien-Skies#414]
Used three rudders, 4 sticks in length. Connected them to the helm using a relay. Yet cannot steer the ship. The rudders themselves turn, but the ship doesn't budge at all. Any help?

**Comment by Electronica27** [comment]
This is currently being worked on, for the time being try using either the plasma engines or the plasma cannons to turn the ship with redstone. Only smaller ships can really turn well with rudders at the moment.

**Comment by RaydenX77** [comment]
oh... okay. i'll just keep it on for props then.
