### ISSUE TITLE
[1.0.1] Crash when moving blocks with Funky Locomotion

### ISSUE THREAD

**Issue by Renniuq** [ValkyrienSkies/Valkyrien-Skies#417]
I wasn't expecting it to work well on a ship, but thought I'd test in case it did work - it seems to be a rendering issue, with the entire world unloading when the block is moved, then promptly crashing. Upon loading back into the world, the blocks do seem to have been moved correctly though.

It seems to happen whether the frames moved are on a ship or not, and even if there aren't any ships currently in the world when the frames are moved. I'm not sure if this would have to be fixed on your end, or on FunkyLocomotion's.

Tested with:
- Valkyrien Skies Control 1.0.1
- Valkyrien Skies 1.0.0
- Valkyrien Skies World 1.0.0
- Funky Locomotion 1.1.2.
- JEI 4.16.1.301

(for that test I had to change FunkyLoco's config to be 0 RF/block moved, since there's no RF generation in those mods, but, that shouldn't matter since it also happened when RF powered in a larger pack I found it in to start)

Using forge 14.23.5.2854

[crash-2020-09-27_16.28.26-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/5289107/crash-2020-09-27_16.28.26-client.txt)

**Comment by Tri0de** [comment]
It looks like they're sending the world load event more than once, or maybe they just forgot to send the world unload event?

Either way I think VS is probably the only mod that would care about the world events so much. I can make this send a warning message instead of crashing.

**Comment by Tri0de** [comment]
Fixed in 8124fd9edb053022bfb398958ee18d14d63c5f6b
