### ISSUE TITLE
Crash to launcher - Exit code 0, caused by vanillafix specifically

### ISSUE THREAD

**Issue by ultrak2k** [ValkyrienSkies/Valkyrien-Skies#423]
So I was assembling a personal modpack, until I put in valk skies, and then it started crashing
Narrowed down what the mods causing this are, and it turns out that somehow vanillafix is causing this
Crash log:[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/5345646/latest.log)
Mod list^ ![image](https://user-images.githubusercontent.com/43084360/95421544-1234dd00-099a-11eb-9f95-ede0cc6b0570.png)

**Comment by ASk8716** [comment]
you can "fix" that problem by downgrading vanillafix to 1.0.10-99

**Comment by ChromaPIE** [comment]
Try to rename the vanillafix's jar to "_VanillaFix-1.0..blablabla", that is to say, add a "_". Should be working.

**Comment by ultrak2k** [comment]
ah yeah i did that a while back
