### ISSUE TITLE
Speed telegraph changes speed but lever doesn't move

### ISSUE THREAD

**Issue by fearlessphoenix** [ValkyrienSkies/Valkyrien-Skies#425]
When I change the speed with the telegraph, the speed of the ship does change but the lever stays in the 'stop' position

**Comment by davigsm** [comment]
i have the same problem

**Comment by davigsm** [comment]
in version 10.0 this bug don't occurs

**Comment by shanzenos** [comment]
Someone should close this, it seems to be fixed.

**Comment by Tri0de** [comment]
> Someone should close this, it seems to be fixed.

You got it chief!
