### ISSUE TITLE
Giant Propeller crash

### ISSUE THREAD

**Issue by HassaFelipe** [ValkyrienSkies/Valkyrien-Skies#426]
I made a minecraft instante on multi mc for making some tests with the Valkyrien Skies but my world crash went i make a giant propeller multi-block, and since then i can't open my world, i don't know why its happens and neither know understand a crashlog.
Please, if any of you can help me i will be immensely grateful.

Sorry me for my bad english... i am trying to improve.
Thanks. 

[crash-2020-10-15_09.03.41-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/5387072/crash-2020-10-15_09.03.41-server.txt)

**Comment by Sunspot0411** [comment]
what vs version did you use? it seems you were not using valkyrien skies 1.1.0 and vs-control 1.1.0

**Comment by Tri0de** [comment]
Update Valkyrien Skies to 1.1.0
