### ISSUE TITLE
Ghostblock-Ships

### ISSUE THREAD

**Issue by DynamicGoose** [ValkyrienSkies/Valkyrien-Skies#434]
If I build a ship and then assamble it. The Blocks won't be interactable anymore and there is no way to delete/destroy them.

**Comment by Tri0de** [comment]
Log pls

**Comment by DynamicGoose** [comment]
I'm not at home currently, so I don't have access to it. I'm back home in two days.

**Comment by DeltaNedas** [comment]
liar

**Comment by DynamicGoose** [comment]
sorry,
screenshots and two logs
2020-11-28-7 is the one where I first encountered the problem
latest.log is from today where I intentionally caused it
![2021-01-04_09 40 28](https://user-images.githubusercontent.com/75172915/103517123-ed091b00-4e71-11eb-9c72-43d1684b8432.png)
![2021-01-04_09 37 05](https://user-images.githubusercontent.com/75172915/103517125-ee3a4800-4e71-11eb-8056-8615dec219a4.png)
![2021-01-04_09 37 12](https://user-images.githubusercontent.com/75172915/103517127-eed2de80-4e71-11eb-9187-f9ef1b4b2477.png)
![2021-01-04_09 37 29](https://user-images.githubusercontent.com/75172915/103517131-eed2de80-4e71-11eb-8b7a-7c0c612fad93.png)
![2021-01-04_09 37 51](https://user-images.githubusercontent.com/75172915/103517132-ef6b7500-4e71-11eb-9d1c-b69e3445e5e2.png)

[2020-11-28-7.log](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/5763776/2020-11-28-7.log)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/5763778/latest.log)

**Comment by DeltaNedas** [comment]
@DynamicGoose this was fixed a few days ago
