### ISSUE TITLE
Rudders are severely delayed/don't work

### ISSUE THREAD

**Issue by Gamershy** [ValkyrienSkies/Valkyrien-Skies#442]
I searched before in the bug reports for this issue, and I did find it, however, it wasn't exactly in as much detail as I've found.

The issue where Rudders don't seem to work with larger ships is already known, however, I've found somen ew information about it.
When reading the bug report, it was said that rudders work with smaller ships, so I built a very small ship, very basic, complete with speed control, lift lever, the steering wheel, and of course all the parts necessary for an air ship when you're not using the captains chair. Upon starting it up, everything worked except for the steering. So I decided to just fly straight for a while, and experiment more with the ship and what was possible. After about a minute or so of flight, the ship had suddenly begun steering in the direction I attempted to prior, and was holding that steering angle for an excessively long amount of time. Based on this observation, it appears that rather than the rudders failing to work, they indeed are working, but something in the code that makes the ship rotate slower or react slower with higher mass seems to be broken, resulting in severely delayed turning with rudders. This would explain why it seems that larger airships refuse to work with the rudder at all- the mass is too large and causes the ship to react so slowly that you'd likely need to sit for several minutes- or even hours- for the ship to respond. Hopefully this helps with this admittedly serious issue. Perhaps a temporary patch would be to add a config option to enable/disable how the mass affects steering your airship?

Also, amazing work with this mod. I remember in my earlier days of playing MC, a friend showed me a server that added airships, but they were just chunks of blocks being moved, and turning was exclusively 90 degree angles as a result. This gives the same magic that the plugin gave, but so much better. Hopefully one day this mod can become near perfect.

PS. I'm so using this to cheese late game RLCraft.

**Comment by CJACOBSON32** [comment]
Having this exact same issue. Waiting doesn't seem to help for me. I've been steering the same small vessel for 10 minutes and it hasn't turned at all. Was there a point at which this bug didn't occur? If so, it seems weird to introduce such a fundamental bug in a public release.

**Comment by Gamershy** [comment]
Something to add to this: I just built a test ship, and for some odd reason, the ship responds to steering left perfectly fine, however, when the wheel is neutral, the ship will sometimes steer left, sometimes go straight, and when trying to steer right, it only goes straight. Very aggravating at this point... you release a patch to fix some random compatibility issues as well as some cosmetic fixes, but don't patch this issue that makes normal airships entirely unusable without an addon mod. I'd rather not have to use the captains chair as that results in a very cheaty experience when flying, and excessive sensitivity with flight.. Please put this higher up on the priority list.

**Comment by Raptor22a** [comment]
> Something to add to this: I just built a test ship, and for some odd reason, the ship responds to steering left perfectly fine, however, when the wheel is neutral, the ship will sometimes steer left, sometimes go straight, and when trying to steer right, it only goes straight. Very aggravating at this point... you release a patch to fix some random compatibility issues as well as some cosmetic fixes, but don't patch this issue that makes normal airships entirely unusable without an addon mod. I'd rather not have to use the captains chair as that results in a very cheaty experience when flying, and excessive sensitivity with flight.. Please put this higher up on the priority list.

What Is there an addon mod that fixes this, or are you just giving an example?

**Comment by Gamershy** [comment]
> > Something to add to this: I just built a test ship, and for some odd reason, the ship responds to steering left perfectly fine, however, when the wheel is neutral, the ship will sometimes steer left, sometimes go straight, and when trying to steer right, it only goes straight. Very aggravating at this point... you release a patch to fix some random compatibility issues as well as some cosmetic fixes, but don't patch this issue that makes normal airships entirely unusable without an addon mod. I'd rather not have to use the captains chair as that results in a very cheaty experience when flying, and excessive sensitivity with flight.. Please put this higher up on the priority list.
> 
> What Is there an addon mod that fixes this, or are you just giving an example?

Giving an example.

**Comment by creeperdeking** [comment]
Yeah same very buggy experience with the rudder inside a very simple ship (sometimes it works but only for one direction, sometimes it does not work at all despite rotating and a moving ship). Is it actually possible to build a ship that works? I never managed to do it.

**Comment by SangurianSoul** [comment]
While it may be delayed, it is absolutely terrible for me, to the point that it doesn't even seem to work for small ships. I just downloaded the mod and  I have a small airship (platform 3x5) with the absolute bare essentials, and four of the largest sizes Rudders, and while they turn in animation, they do not turn the ship. At slow, half, or full speeds. It will start to for a moment, then it just will not any more, despite continuing to turn the wheel.

Also, twice now, randomly, while putting along (straight) ill suddenly climb to heights unattainable by Minecraft (Over 500 at one point) and shaking violently. This lasts for 30 seconds or so, before I plummet down and the ship catches itself at its altitude. I'm not sure if its related, but it felt like it came out of nowhere, maybe do to the delay issue with the turning?

**Comment by Gamershy** [comment]
Alright, this has reached a point where the developers very clearly have no care in their mod outright not working. I'm done. Fuck this mod.

**Comment by HungryHungrySourceCode** [comment]
LoL this guy is pissed. If there's any devs that are actively working on this mod and read this thread, thankyou for all the hard work you do and time you put into this mod. The scale and scope of this mod is massive, I hope development on this continues.

**Comment by Gamershy** [comment]
> LoL this guy is pissed. If there's any devs that are actively working on this mod and read this thread, thankyou for all the hard work you do and time you put into this mod. The scale and scope of this mod is massive, I hope development on this continues.

Correct, I am pissed, this has been an issue for over half a year (likely longer based on other issues) and the devs focus instead on random compatibility issues instead of an issue that literally makes the mod unusable.

**Comment by Rubydesic** [comment]
yikes. don't act like you have some sort of support contract with us. the mod is volunteer work entirely nobody's working here full time. and we will not be fixing issues with this control system, but it's open source and licensed under apache 2, so you are free to fix it yourself if you know how to program.

here is the link if you are interested: https://github.com/ValkyrienSkies/Valkyrien-Skies-Control
if you have a problem with setting up the development workspace you can ping me in the discord with @Rubydesic.

**Comment by DeltaNedas** [comment]
doesnt even apply anymore since vs control won't exist in vs 2
