### ISSUE TITLE
Can not join server which have no VS installed

### ISSUE THREAD

**Issue by ShiratsuYudachi** [ValkyrienSkies/Valkyrien-Skies#450]
Tested with:
Paperspigot
Catserver
Sponge
Forge

VS version:
core: 1.1.1
control: 1.1.0
world: 1.0.0

Client side will only get a message of 'Disconnected'

and server side got these:
```
[15:21:38] [User Authenticator #2/INFO]: UUID of player Yuudachi_Kai2 is 06327b52-b5e1-300f-bfeb-cc08582d2773
[15:21:38] [Server thread/INFO]: Yuudachi_Kai2[/192.168.1.108:6950] logged in with entity id 39 at ([world]-427.9216714903352, 66.0, 364.1323587100114)
**[15:21:39] [Server thread/INFO]: Yuudachi_Kai2 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/14 (PacketPlayInPositionLook) was larger than I expected, found 58 bytes extra whilst reading packet 14**
[15:21:39] [Server thread/INFO]: Yuudachi_Kai2 left the game
```
if server installed VS, I can join normally

**Comment by ShiratsuYudachi** [comment]
tested with VS 1.1.3, and it persist

**Comment by Rubydesic** [comment]
This is intended behaviour. Do not join servers without VS with VS installed.

**Comment by TheFlash787** [comment]
May I ask why this is @Rubydesic ? Many larger servers that use your mod will have a hub-world for their players to access during server restarts. This intended behaviour makes the mod entirely incompatible with networks and will be removed. Is there any way you could add a safety hook?
