### ISSUE TITLE
[Feature Suggestion] Add config option to modify valkyrium ore spawning

### ISSUE THREAD

**Issue by TheQKnight** [ValkyrienSkies/Valkyrien-Skies#454]
I think it would be neat if you could disable the spawning of valkyrium ore for people who wanted to add an alternative way of obtaining valkyrium crystals. Most mods implement a config option to modify their ore spawns, so i couldnt image this would be difficult to do.

**Comment by DeltaNedas** [comment]
99% sure this was added months ago

**Comment by TheQKnight** [comment]
ah yes i see, the configs are split into separate files. Thank you for pointing that out.
