### ISSUE TITLE
Lighting not updating when assembling ships (Pitch black ships)

### ISSUE THREAD

**Issue by Mrleplayz** [ValkyrienSkies/Valkyrien-Skies#455]
-Latest curseforge release.
-Mods installed : VS, VS control, VS world, JourneyMap, NotEnoughIDs, Worldedit
-Ship block count is above 150,000 however some people have confirmed it happens on smaller ships (reported ~60 block long)
-Placing a light source down will update the lighting in the area around the block, to fix the ship it has to be updated area by area.

![2021-01-03_13 33 03](https://user-images.githubusercontent.com/43085859/103478765-305b7f00-4dc9-11eb-95db-b5b6d6b4da81.png)
![2021-01-03_13 33 39](https://user-images.githubusercontent.com/43085859/103478759-29cd0780-4dc9-11eb-8758-aa32c5c21c85.png)
![2021-01-03_13 34 04](https://user-images.githubusercontent.com/43085859/103478763-2e91bb80-4dc9-11eb-8193-2af359e0c458.png)
![2021-01-03_13 33 52](https://user-images.githubusercontent.com/43085859/103478822-9c3de780-4dc9-11eb-8b36-1d7742a4a9b3.png)
![2021-01-03_13 33 56](https://user-images.githubusercontent.com/43085859/103478824-9e07ab00-4dc9-11eb-9e98-8c8e55893329.png)
![2021-01-03_13 33 58](https://user-images.githubusercontent.com/43085859/103478826-9f38d800-4dc9-11eb-9f52-0aba8b59842c.png)

**Comment by copperwarrior** [comment]
Can confirm, this is particularly common on ships that are covered in some way, i.e. large air balloons.

**Comment by DeltaNedas** [comment]
had this happen to my flat piece of 4x6 wood

**Comment by Tri0de** [comment]
Try latest jenkins I just fixed it.
