### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION crash on startup with multiple mods

### ISSUE THREAD

**Issue by TheQKnight** [ValkyrienSkies/Valkyrien-Skies#458]
Out of 22 startups, 12 of my startups with this mod installed have resulted in a EXCEPTION_ACCESS_VIOLATION error. I have a few other mods installed as well, which might be conflicting with this mod.

I have attached my hs_err_pid log and latest.log as pastebin will not allow me to post anything there.
[hs_err_pid2836.log](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/5762524/hs_err_pid2836.log)
[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/5762525/latest.log)

**Comment by Tri0de** [comment]
I don't see it in your logs

**Comment by TheQKnight** [comment]
It seems to crash before the game even starts loading, which might be why it doesn't show in logs

**Comment by TheQKnight** [comment]
I don't know what changed, but im not having the issue anymore. Probably something with mixins.
