### ISSUE TITLE
Game crashing when tolded to assemble ship Error code: "Error: java.lang.ClassCastException:"

### ISSUE THREAD

**Issue by dhsTStroud** [ValkyrienSkies/Valkyrien-Skies#473]
All the info I know to give, please help!

"The game crashed whilst unexpected error
Error: java.lang.ClassCastException: net.minecraft.world.chunk.Chunk cannot be cast to org.valkyrienskies.mod.client.render.ITileEntitiesToRenderProvider
Exit Code: -1"

hastebin link - hastebin is not working atm but I'll update this if it starts working bc despite it all I still love hastebin
pastebin link - https://pastebin.com/iBWU0JUL
privatebin link- https://privatebin.net/?8f5af83e7a13219d#ANPHvE74nFqLb7dJKNYCMwNJHQw4QVEcfUBmUCgCB4ui
ghostbin link - https://ghostbin.com/paste/shSoO
justpastit link - https://justpaste.it/4gtcc

I was snooping the other topics to see if I could fix this myself and a lot of the pastebin links were gone so maybe I can avoid that happening with mine lol.

**Comment by Rubydesic** [comment]
Try adding a bunch of brackets to the front of the name of the valkyrien skies JAR, such as `[[[[valkyrienskies.jar`

**Comment by dhsTStroud** [comment]
Okay, that worked but now half my ship is really dark for some reason? 
![image](https://user-images.githubusercontent.com/38190293/106099067-b2f10900-60ff-11eb-8eee-0c3d03ea4778.png)

**Comment by dhsTStroud** [comment]
That did work though, thank you so much!

**Comment by dhsTStroud** [comment]
it seems to be the shadow from the sails
