### ISSUE TITLE
Hope my ship back to blocks and share the map built with v0.9

### ISSUE THREAD

**Issue by Zuosizhu** [ValkyrienSkies/Valkyrien-Skies#475]
Hello, I'm a fresh player with ValkyrienWarfareRevamped-1.12.2-v0.9_alpha-full.jar. I built CVL-48 in the game and turned the blocks to a ship. However, I cannot share my works with my friends unless they also install the mod. I learned that v1.0 may help but they are actually two mods. If it won't take much time, maybe you can release a mod to turn ships back to blocks compatible to v0.9.
Sorry for my poor English and my unreasonable requests.
Best wishes to you.

**Comment by Tri0de** [comment]
bruh

**Comment by Rubydesic** [comment]
Check the block coordinates with F3 (in-game)

then open MCEdit and copy all of the ship blocks back into your world.

**Comment by Zuosizhu** [comment]
> Check the block coordinates with F3 (in-game)
> 
> then open MCEdit and copy all of the ship blocks back into your world.

Are they extremely large numbers?like XYZ=-29919578 128 -29920072

**Comment by Zuosizhu** [comment]
> Check the block coordinates with F3 (in-game)
> 
> then open MCEdit and copy all of the ship blocks back into your world.

Glad to see the ship. I'm very grateful.

**Comment by Rubydesic** [comment]
Glad to hear it. Enjoy the update.
