### ISSUE TITLE
Culling Thread crashed

### ISSUE THREAD

**Issue by Killfrop** [ValkyrienSkies/Valkyrien-Skies#517]
assembling a ship on a multiplayer server and had a crash on the client, but the server was running fine. crash-log gave the description "Culling Thread crashed", crash report is attached
[crash-2022-02-03_17.39.05-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies/files/7997034/crash-2022-02-03_17.39.05-client.txt)
.

**Comment by Rubydesic** [comment]
Looks like an incompatibility with the "entity culling" mod
