### ISSUE TITLE
Valkyrien-Skies-2 compile issue someone can help me ?

### ISSUE THREAD

**Issue by johnburn068** [ValkyrienSkies/Valkyrien-Skies#519]
C:\Users\Utilisateur> cd C:\Users\Utilisateur\Desktop\Valkyrien-Skies-2-main

C:\Users\Utilisateur\Desktop\Valkyrien-Skies-2-main>gradlew build

> Configure project :
Architect Plugin: 3.4.130

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Utilisateur\Desktop\Valkyrien-Skies-2-main\build.gradle' line: 43

* What went wrong:
A problem occurred evaluating root project 'valkyrienskies'.
> java.lang.UnsupportedClassVersionError: net/fabricmc/loom/bootstrap/LoomGradlePluginBootstrap has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Comment by StewStrong** [comment]
Use java 17

**Comment by johnburn068** [comment]
I downloaded it but there is a new error.



C:\Users\Utilisateur\Desktop\Valkyrien-Skies-2-main>gradlew build
Starting a Gradle Daemon, 3 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :
Architect Plugin: 3.4.130
Architectury Loom: 0.11.0.244

> Configure project :common
Processing file: minecraft-project-@common-merged-named.jar
:remapping 1 mods (TinyRemapper, intermediary -> named)
:remapped 1 mods (TinyRemapper, intermediary -> named) in 4.958 s
:remapping sources

> Configure project :fabric
Processing file: minecraft-project-@fabric-merged-named.jar
:remapping 46 mods (TinyRemapper, intermediary -> named)
:remapped 46 mods (TinyRemapper, intermediary -> named) in 3.356 s
:remapping sources

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':fabric'.
> Could not resolve all files for configuration ':fabric:architecturyTransformerClasspath'.
   > Could not find org.valkyrienskies.core:vs-core:1.0.
     Searched in the following locations:
       - file:/C:/Users/Utilisateur/Desktop/Valkyrien-Skies-2-main/.gradle/loom-cache/remapped_mods/org/valkyrienskies/core/vs-core/1.0/vs-core-1.0.pom
       - https://maven.fabricmc.net/org/valkyrienskies/core/vs-core/1.0/vs-core-1.0.pom
       - https://libraries.minecraft.net/org/valkyrienskies/core/vs-core/1.0/vs-core-1.0.pom
       - https://libraries.minecraft.net/org/valkyrienskies/core/vs-core/1.0/vs-core-1.0.jar
       - https://maven.minecraftforge.net/org/valkyrienskies/core/vs-core/1.0/vs-core-1.0.pom
       - https://repo.maven.apache.org/maven2/org/valkyrienskies/core/vs-core/1.0/vs-core-1.0.pom
       - file:/C:/Users/Utilisateur/.gradle/caches/fabric-loom/1.0/vs-core.jar
       - file:/C:/Users/Utilisateur/Desktop/Valkyrien-Skies-2-main/.gradle/loom-cache/1.0/vs-core.jar
       - https://maven.architectury.dev/org/valkyrienskies/core/vs-core/1.0/vs-core-1.0.pom
     Required by:
         project :fabric

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 43s
