### ISSUE TITLE
Vivecraft

### ISSUE THREAD

**Issue by shadowbolt79** [ValkyrienSkies/Valkyrien-Skies#98]
Ship chunk rendering seems to somehow mess with Vivecraft's HMD rendering. Head cannot tilt. The Camera's render matrix needs to be preserved for that to work correctly, so push/popping a matrix might enable that to render correctly.

Other issues include the ship moving without you, but that might not be fixable by you alone. Could probably be fixed by putting down a chair and sitting in it while you steer the ship.

**Comment by MeDomi** [comment]
I have kind off the same issue, it changes the tilt direction off your view.
You tilt left it goes right and the other way around
This issue occurred in vivecraft-1.12.2-jrbudda-9-r6-forge with Valkyrien Warfare 0.9 pre release 5+
and older 1.12 Valkyrien.
I didn't really try using the ships, this tilt bug is the only thing I found but sadly it game breaking =(

**Comment by DeltaNedas** [comment]
stop using old versions its probably fixed in latest breaking/1.0 build

**Comment by MeDomi** [comment]
Jea I wrote that before I read the update log.
Thought its just a little update and by the way it really works.
Should have tried it out first.

Ok the newest version fixed it

**Comment by DeltaNedas** [comment]
jannies pls close @Rubydesic
